format_version: 10

pipelines:
  test-pipeline:
    group: "test-group"
    label_template: "${COUNT}"
    materials:
      app-repo:
        type: git
        url: "https://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@github.com/Pansaar/app-gpt-embeded.git"
        branch: "main"
    
    stages:
      - Build:
          fetch_materials: true
          jobs:
            BuildJob:
              clean_workspace: true
              resources:
                - BuildJob
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        rm -rf vite-frontend
                        git clone --depth 1 https://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@github.com/Pansaar/app-gpt-embeded.git vite-frontend
                        cd vite-frontend
                        rm -rf node_modules package-lock.json
                        npm install
                        npm run build

      - Deploy:
          fetch_materials: true
          jobs:
            DeployJob:
              clean_workspace: true  
              resources:
                - BuildJob  
                - DeployJob
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        if ! command -v aws &> /dev/null; then 
                          echo "AWS CLI not found!"; 
                          exit 1; 
                        fi

                        aws s3 cp vite-frontend/dist/index.html s3://bay-auto-chatbot-frontend/index.html \
                          --metadata-directive REPLACE \
                          --cache-control "no-cache, no-store, must-revalidate, max-age=0" \
                          --expires 0

                        aws s3 sync vite-frontend/dist/assets/ s3://bay-auto-chatbot-frontend/assets/ --delete \
                          --metadata-directive REPLACE \
                          --cache-control "no-cache, no-store, must-revalidate, max-age=0" \
                          --expires 0

environments:
  test-env:
    pipelines:
      - test-pipeline
    agents:
      - bc4933d0-8d6a-4f5e-b37f-15945aacde3f
