format_version: 10

pipelines:
  test-pipeline:
    group: "test-group"
    label_template: "${COUNT}"
    materials:
      app-repo:
        type: git
        url: "https://github.com/Pansaar/app-gpt-embeded.git"
        branch: "main"
    
    stages:
      - Build:
          fetch_materials: true 
          jobs:
            BuildJob:
              clean_workspace: true  # ✅ Forces a clean workspace at job start
              resources:
                - BuildJob
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        echo "🚀 Cleaning old build files..."
                        rm -rf vite-frontend/dist  # ✅ Ensure old files are removed
                        if [ ! -d "vite-frontend" ]; then echo "vite-frontend directory not found!"; exit 1; fi
                        cd vite-frontend
                        npm install
                        npm run build

      - Deploy:
          fetch_materials: true
          jobs:
            DeployJob:
              clean_workspace: true  # ✅ Ensures no old files remain
              resources:
                - BuildJob
                - DeployJob
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        if ! command -v aws &> /dev/null; then echo "AWS CLI not found!"; exit 1; fi
                        echo "🚀 Uploading latest index.html..."
                        aws s3 cp vite-frontend/dist/index.html s3://bay-auto-chatbot-frontend/index.html \
                          --metadata-directive REPLACE \
                          --cache-control "no-cache, no-store, must-revalidate" \
                          --expires 0

                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        echo "🚀 Syncing assets to S3..."
                        aws s3 sync vite-frontend/dist/assets/ s3://bay-auto-chatbot-frontend/assets/ --delete \
                          --metadata-directive REPLACE \
                          --cache-control "no-cache, no-store, must-revalidate" \
                          --expires 0
