format_version: 10

pipelines:
  test-pipeline:
    group: "test-group"
    label_template: "${COUNT}"
    materials:
      app-repo:
        type: git
        url: "https://github.com/Pansaar/app-gpt-embeded.git"
        branch: "main"
    
    stages:
      - Build:
          fetch_materials: true  # ✅ Explicitly fetch materials
          jobs:
            BuildJob:
              clean_workspace: true  # ✅ Moved to job level
              resources:
                - BuildJob
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        if [ ! -d "vite-frontend" ]; then echo "vite-frontend directory not found!"; exit 1; fi
                        cd vite-frontend
                        npm install
                        npm run build

      - Deploy:
          fetch_materials: true
          jobs:
            DeployJob:
              resources:
                - DeployJob
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        if ! command -v aws &> /dev/null; then echo "AWS CLI not found!"; exit 1; fi
                        aws s3 cp vite-frontend/dist/index.html s3://bay-auto-chatbot-frontend/index.html
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        aws s3 sync vite-frontend/dist/assets/ s3://bay-auto-chatbot-frontend/assets/ --delete

environments:
  test-env:
    pipelines:
      - test-pipeline
    agents:
      - PansaarMacs-Laptop.local # Replace with actual GoCD agent ID
