trigger:
- main

pool:
  name: self-hosted  # Specify your custom self-hosted agent pool

steps:
- checkout: self
  fetchDepth: 1

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Publish build output as artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'build'  # Change this if your build output is in another folder like 'dist'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
