trigger:
  - main

pool:
  name: self-hosted  # Specify your self-hosted agent pool

variables:
  ARTIFACT_NAME: "drop"
  ARTIFACT_PATH: "$(Build.ArtifactStagingDirectory)/drop"
  APP_NAME: "web-app-test"  # Your Azure App Service name
  RESOURCE_GROUP: "test-resource-group"  # Your Azure resource group
  APP_PACKAGE_PATH: "$(Build.ArtifactStagingDirectory)/drop"

steps:
  - checkout: self
    fetchDepth: 1

  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  # Install dependencies and build project
  - script: |
      npm install
      npm run build
    displayName: "Install dependencies and build"

  # Publish build output as an artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "vite-frontend/dist"  # Ensure this is the correct build path
      artifactName: "$(ARTIFACT_NAME)"
      publishLocation: "Container"
    displayName: "Publish Build Artifacts"

  # Download build artifacts
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: "current"
      downloadType: "single"
      artifactName: "$(ARTIFACT_NAME)"
      downloadPath: "$(ARTIFACT_PATH)"
    displayName: "Download Build Artifacts"

  # Deploy to Azure App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: "Azure subscription 1"  # Service connection in Azure DevOps
      appName: "$(APP_NAME)"
      resourceGroupName: "$(RESOURCE_GROUP)"
      package: "$(APP_PACKAGE_PATH)"  # Ensure this is the correct path to `dist`
      runtimeStack: "NODE|20-lts"
    displayName: "Deploy to Azure App Service"
