trigger:
- main

pool:
  name: self-hosted  # Specify your self-hosted agent pool

steps:
- checkout: self
  fetchDepth: 1

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Build the project
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Publish build output as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'vite-frontend/dist'  # Ensure this is the correct path
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

# Ensure artifacts are available in the deployment job
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Download Build Artifacts'

# Deploy via SCP
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'my-ssh-service'  # Must match the SSH service connection name
    sourceFolder: '$(Build.ArtifactStagingDirectory)/drop'  # Ensure artifact path is correct
    contents: '**'  # Transfer all files
    targetFolder: '/var/www/html'  # Destination path on the remote server
    readyTimeout: '20000'
    cleanTargetFolder: true
  displayName: 'Deploy to 20.189.75.24'

# Fix file permissions after deployment
- script: |
    sudo chmod -R 755 /var/www/html
    sudo chown -R www-data:www-data /var/www/html
    sudo systemctl restart nginx
  displayName: 'Fix permissions & Restart Nginx'
  condition: succeeded()
