trigger:
  - main

pool:
  name: self-hosted  # Specify your self-hosted agent pool

variables:
  - group: StaticWebAppSecrets  # Link the Variable Group
  - name: ARTIFACT_NAME
    value: "drop"
  - name: ARTIFACT_PATH
    value: "$(Build.ArtifactStagingDirectory)/drop"
  - name: APP_NAME
    value: "web-app-test"  # Your Azure App Service name
  - name: RESOURCE_GROUP
    value: "test-resource-group"  # Your Azure resource group
  - name: APP_PACKAGE_PATH
    value: "$(Build.ArtifactStagingDirectory)/drop"

steps:
  - checkout: self
    fetchDepth: 1

  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  # Install dependencies and build project
  - script: |
      npm install
      npm run build
    displayName: "Install dependencies and build"

  # Publish build output as an artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "vite-frontend/dist"  # Ensure this is the correct build path
      artifactName: "$(ARTIFACT_NAME)"
      publishLocation: "Container"
    displayName: "Publish Build Artifacts"

  # Download build artifacts
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: "current"
      downloadType: "single"
      artifactName: "$(ARTIFACT_NAME)"
      downloadPath: "$(ARTIFACT_PATH)"
    displayName: "Download Build Artifacts"

  # Deploy to Azure Static Web App (Corrected indentation) check
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      app_location: "vite-frontend/dist"  # The folder containing the built frontend
      output_location: ""  # Leave blank for static sites
    displayName: "Deploy to Azure Static Web App"
