trigger:
  - main

pool:
  name: self-hosted # Specify your self-hosted agent pool

steps:
  - checkout: self
    fetchDepth: 1

  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  # Build the project
  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  # Publish build output as an artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "vite-frontend/dist" # Ensure this is the correct path
      artifactName: "drop"
      publishLocation: "Container"
    displayName: "Publish Build Artifacts"

  # Ensure artifacts are available in the deployment job
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: "current"
      downloadType: "single"
      artifactName: "drop"
      downloadPath: "$(Build.ArtifactStagingDirectory)"
    displayName: "Download Build Artifacts"

  # Deploy via SCP to a temporary directory
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: "my-ssh-service"
      sourceFolder: "$(Build.ArtifactStagingDirectory)/drop" # Ensure artifact path is correct
      contents: "**" # Transfer all files
      targetFolder: "/home/pansaar/deployment-temp" # Temporary deployment folder
      readyTimeout: "20000"
      cleanTargetFolder: true
    displayName: "Deploy to 20.189.75.24 (Temp Folder)"

  - script: |
      # Debug - ensure files exist in deployment folder
      ls -lah /home/pansaar/deployment-temp

      # Remove old files and move the new files
      rm -rf /var/www/html/*
      mv /home/pansaar/deployment-temp/* /var/www/html/

      # Correct the permissions of the files for web server
      chown -R pansaar:pansaar /var/www/html  # Ensure proper ownership
      chmod -R 775 /var/www/html  # Ensure proper permissions
      systemctl restart nginx  # Restart nginx to serve the files
    displayName: 'Move Files & Restart Nginx'
    condition: succeeded()

