version: '3.8'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/app      
    working_dir: /app/src/api
    command: ["bun", "run", "./index.ts"]

  frontend-service:
    image: node:18
    working_dir: /app/sec
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build && npm run start -- --host 0.0.0.0"
    ports:
      - "4173:4173"
    

