FROM node:18 AS base

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:$PATH"

WORKDIR /app

COPY package*.json bun.lockb* ./

RUN bun install --frozen-lockfile

COPY src/api /app/src/api

EXPOSE 3000

WORKDIR /app/src/api

CMD ["bun", "run", "./index.ts"]
