name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: |
          cd vite-frontend 
          npm install

      - name: Build the Project
        run: |
          cd vite-frontend
          npm run build

      # AWS S3 Deployment
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::891376919848:role/s3-allow-github-chatgpt-embeded
          aws-region: ap-southeast-1

      - name: Deploy `index.html` to S3 
        run: |
          aws s3 cp vite-frontend/dist/index.html s3://bay-auto-chatbot-frontend/index.html

      - name: Deploy `assets/` folder to S3
        run: |
          aws s3 sync vite-frontend/dist/assets/ s3://bay-auto-chatbot-frontend/assets/ --delete

      # Azure App Service Deployment
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Set Node.js Version & Disable Oryx Build
      - name: Configure Azure App Service
        run: |
          az webapp config appsettings set --resource-group test-resource-group --name test-web-app-pansaar --settings WEBSITE_NODE_DEFAULT_VERSION=20 SCM_DO_BUILD_DURING_DEPLOYMENT=false

      # ✅ Deploy Full `dist/` to Azure Web App (New Method)
      - name: Deploy Full `dist/` to Azure Web App
        run: |
          cd vite-frontend/dist
          zip -r ../dist.zip .  # Ensure only contents inside `dist/` are zipped
          cd ..
          az webapp deploy --resource-group test-resource-group --name test-web-app-pansaar --src-path dist.zip

      # 🔄 Restart Azure App Service After Deployment
      - name: Restart Azure Web App
        run: |
          az webapp restart --name test-web-app-pansaar --resource-group test-resource-group
